CREATE TABLE devices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type ENUM('Mobile', 'Desktop', 'Tablet', 'SmartTV', 'Console') NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
