CREATE TABLE ad_slot_sizes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  size VARCHAR(20) NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
