CREATE TABLE genders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  label ENUM('Male', 'Female') NOT NULL UNIQUE,                 
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
